site_name: Service design guidelines
site_url: https://vondacho.github.io/arch-service-design-guidelines/
repo_url: https://github.com/vondacho/arch-service-design-guidelines/
repo_name: GitHub repository
docs_dir: doc

nav:
  - Home: index.md
  - Reference guidelines: reference_guidelines.md

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: True

theme: material

extra_css:
  - stylesheets/colors.css
  