name: build

on:
  workflow_dispatch: # Allow to manually trigger the pipeline
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v3

      - name: Deploy to GH pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: ./.github/actions/mkdocs-publish